name: NPM 发布

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: 安装依赖
        run: npm ci

      - name: 运行测试
        run: npm test

      - name: 构建
        run: npm run build

      # 如果是带标签的推送，则发布到 npm
      - name: 发布到 npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 对于非标签的主分支推送，则创建测试版本
      - name: 发布测试版本到 npm
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        run: |
          # 获取当前版本号
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # 创建唯一的预发布标签
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          NEW_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"
          # 更新 package.json 版本
          npm version ${NEW_VERSION} --no-git-tag-version
          # 发布测试版本
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
